version: '3'

services:
  database:
    hostname: db
    container_name: db
    image: postgres:latest
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 30s
      retries: 6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql
    restart: always

  apiflask-first:
    build: .
    hostname: apiflask_first
    healthcheck:
      interval: 5m
      timeout: 30s
      retries: 3
    ports:
      - '5000:5000'
    command: "python run.py"
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy



